version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
init:
- cmd: set GITVERSION_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
artifacts:
- path: '**/*nupkg'
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
